import { Box } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import TextAndImageContainer from "../components/shared/TextAndImageContainer";
import HomeGalleryContainer from "../components/home/HomeGalleryContainer";
import FeaturesContainer from "../components/shared/FeaturesContainer";

const Home: NextPage = () => {
  const [data, setData] =useState([{src: '', heading: '', description: '', cta: ''}]);

  useEffect(() => {
    fetch('/api/home')
      .then((response) => response.json())
      .then((info) => setData(info));
  }, [])

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box>
        {data.map((info) => {
          return <TextAndImageContainer data={info} 
          key={info.src}/>
        })}
        <HomeGalleryContainer/>
        <FeaturesContainer/>
      </Box>
    </div>
  );
};

export default Home;
